### ISSUE TITLE
examples are using "../.." as alias but should be using npm version

### ISSUE THREAD

**Issue by leobastiani** [ArturKalach/react-native-a11y#23]
First of all thank you very much for this amazing library, we are going to use at gympass.com

- `examples/A11ySample` has both `package-lock.json` and `yarn.lock`
- `examples/A11ySample` should be able to run by `npx degit ArturKalach/react-native-a11y/examples/A11ySample .`. But it does use https://www.npmjs.com/package/react-native-a11y as a dependency

Do you accept PRs?

**Comment by ArturKalach** [comment]
Hello @leobastiani, 

First of all, thank you for feedback, I really appreciate this, it makes my work sensible

1. You right, I will remove `package-lock.json` this week. 
2. I am not sure, I have never use `npx degit`, maybe I will write cusome npm commands, but this two directories in examples used for testing `old arch` and `new arch` with latest updates into `../` it's orginized by `babel.config.js` and `metro.config.js`

Feel free to create any PRs, and share ideas. I will be really glad to contributors.


If you are intresting about roadmap:
1. I am going to write some articles about native code and migration to new arch. (Probably create separate library to work with kayboard)
2. There are issue with modals on android side, wanna check whether framgent can be solution, or check how I can use activity for this aims.
3. Add more events for handle keyboard (Long press, press in, press out, key pressed)
4. etc

**Comment by leobastiani** [comment]
`npx degit ArturKalach/react-native-a11y/examples/A11ySample` just copy what is inside this folder without cloning everything. In other words, it should be nice if we could download the example folder only without cloning everything to run and test

I tried to clone the project and run the examples with no success, I was only able to run the example after removing aliases of `react-native-a11y` and then applying `yarn add react-native-a11y`

Another problem is that you could update your library and not update the example folder, I see the latest version now is 0.3.1 and example folder is using 0.2.1 https://github.com/ArturKalach/react-native-a11y/blob/c725463ca0e572bce3fa96d3230df52400a71046/examples/A11yNewArch/ios/Podfile.lock#L659

**Comment by ArturKalach** [comment]
Good point.
I need to think about this. I used this two only for developing purposes and having latest updates from the `../`. Probably I will create a separate branch with examples for `dev` and add changes to `examples` for supporting `npx degit`

It is a little bit difficult to keep everything up to date. I think, I will add changes tomorrow or day after tomorrow.

Thank you again,
I raelly appriciate you sharing exprience

**Comment by ArturKalach** [comment]
Hello,
1. `package-lock.json` has been removed.
2. Dependencies for `master` branch has been updated

If you have any to add, feel free to write back or create a new issue 

Regards and thank you
