### ISSUE TITLE
Support for React Native 0.72

### ISSUE THREAD

**Issue by leobastiani** [ArturKalach/react-native-a11y#39]
Thanks again for this amazing library ❤️
Could you please update readme with informations about RN 0.72?

**Comment by ArturKalach** [comment]
Hello @leobastiani,
Thank you for notification, I am going to check it in some days.
I think there are no a lot of changes, maybe I update library with some changes for supporting old versions of RN and remove this information about compibility at all.

BTW: if you need any feature with a11y, feel free to ask, I already have some ideas, but there no needs no time to implement them) 

Thank you for contributing,

Regards,
Artur Kalach

**Comment by ArturKalach** [comment]
- Readme has been updated
- Old React Native versions support approach has been changed
