### ISSUE TITLE
[Android] useA11yEnabled doesn't return right value if talkback is turned on

### ISSUE THREAD

**Issue by ZioVio** [ArturKalach/react-native-a11y#4]
When I turn the talkback on android the `useA11yEnabled` doesn't change the return value

https://user-images.githubusercontent.com/42906560/193291750-1a563943-e878-43fb-a162-48867c730408.mp4

**Comment by ArturKalach** [comment]
The bug is fixed and on a review, it is going to be fixed with https://github.com/ArturKalach/react-native-a11y/pull/6 and new patch

**Comment by ArturKalach** [comment]
Should be fixed with 0.2.1.
