### ISSUE TITLE
[Android] A11yOrder not working on Android

### ISSUE THREAD

**Issue by ZioVio** [ArturKalach/react-native-a11y#5]
`A11yOrder` component in the example app is not working

https://user-images.githubusercontent.com/42906560/193314697-230b47d9-d0c3-4029-90ae-7e955d4e3157.mp4

**Comment by ArturKalach** [comment]
Fix is created and in PR (see: https://github.com/ArturKalach/react-native-a11y/pull/8). It will be add with next patch

**Comment by ArturKalach** [comment]
Should be fixed.
