### ISSUE TITLE
Missing styling for Pressable component

### ISSUE THREAD

**Issue by RickVellingaa** [ArturKalach/react-native-a11y#77]
# Current behavior 

In one of my projects, since version 0.3.0 of react-native-a11y, a number of styling attributes no longer work, such as border-radius, border-color, etc. I created a project to replicate the issue. In my example I used the Pressable component and as soon as I update the package from 0.2.1 to 0.3.0 (or even 0.4.5), the styling of the borders disappeared.

# Expected behavior 

The styling attributes such as border-radius and border-color should work consistently across different versions of the package. Upgrading the package should not cause the styles to disappear.

# Steps to Reproduce

1. Use version 0.2.1 of react-native-a11y
2. Add border styling to a pressable component
3. Upgrade to version 0.3.0 or above
4. Rebuild the app and the styling will be gone

# Context (Environment)

- React Native version: 0.73.7
- react-native-a11y version: 0.3.0 and above (for bug)
- Platform(s): Android
- Device info: Google Pixel 4

# Detailed Description

Sinsce upgrading to version 0.3.0 of react-native-a11y, specific styling properties like border-radius and border-color are no longer being applied to the Pressable component. This issue persists even with the latest version 0.4.5. It seems like there might have been changes in the package that affect how styles are processed or applied. 

Link to my project: https://github.com/RickVellingaa/a11y-repro
This project has 3 different branches with the different react-native-a11y versions.

**Comment by ArturKalach** [comment]
Hello @RickVellingaa,
Thank you a lot for publishing the issue. Unfortunately, I don't have project to test this package thoroughly, and I am really sorry that you came across with such expiriense. I really appreciate that you make such repport and provide the sample app, you are awesome)

I will check the problems with styles asap, but this package requires a lot of updates.

FYI:
In honest, even `react-native-a11y` is ok to use kit, but I would recomend to check a separate package https://github.com/ArturKalach/react-native-external-keyboard, there are additional features (TextInput focus) and it has better API, additionaly it doesn't require additional configuration. I am going to add new features to `react-native-external-keyboard` firslty.

**Comment by ArturKalach** [comment]
Hello @RickVellingaa,

I found a problem and will publish a fix soon.  The problem appeared becouse of wrong component extending in Android.

**Comment by ArturKalach** [comment]
Hello @ArturKalach ,
Sorry for waiting, there were some problems with NewArch.

Issue has been fixed and added to the `0.4.6` version for both arch.

![photo](https://github.com/ArturKalach/react-native-a11y/assets/112642862/184fa457-be30-487e-8b5d-9c652c3052dc)

**Comment by RickVellingaa** [comment]
Thanks for the help and quick response @ArturKalach! Greatly appreciated 😄

**Comment by ArturKalach** [comment]
There is a lot of work and many things that can be done. Your well-written issue has helped me greatly with this. If you could provide any feedback or ideas, it would be greatly appreciated.

If there aren't any comments or problems, I will close the issue a little bit later.

**Comment by RickVellingaa** [comment]
Hey @ArturKalach, Just tested within my project and everything seems to be working without further issues or bugs. Thanks a lot for the quick response. The issue can be closed!
